FROM x11docker/deepin

RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y \
    firefox \
    gedit \
    vim \
    curl \
    wget \
    htop \
    net-tools \
    dnsutils \ 
    netcat \
    apt-utils \
    iputils-ping \
    iproute2 \
    zip \
    unzip \
    tmux

CMD ["startdde"]
